from selenium.webdriver.common.by import By
from data import LISTING_ITEM_TEXT

LOGIN_BUTTON_HEADER = (By.CSS_SELECTOR, "div.header_flexRow__Xdqv1 > button.buttonSecondary")
NO_ACCOUNT_BUTTON = (By.CSS_SELECTOR, "div.popUp_buttonRow__\\+W8JD > button.buttonSecondary[type='button']")
EMAIL_INPUT = (By.CSS_SELECTOR, "input[name='email']")
PASSWORD_INPUT_1 = (By.CSS_SELECTOR, "input[name='password']")
PASSWORD_INPUT_2 = (By.CSS_SELECTOR, "input[name='submitPassword']")
CREATE_ACCOUNT_BUTTON = (By.CSS_SELECTOR, "div.popUp_buttonRow__\\+W8JD > button.buttonPrimary[type='submit']")
USER_AVATAR = (By.CSS_SELECTOR, "button.circleSmall")
USER_TEXT = (By.CSS_SELECTOR, "h3.profileText")
EMAIL_BORDER = (By.XPATH, "//input[@name='email']/parent::div[@class='input_inputError__fLUP9']")
PWD_1_BORDER = (By.XPATH, "//input[@name='password']/parent::div[@class='input_inputError__fLUP9']")
PWD_2_BORDER = (By.XPATH, "//input[@name='submitPassword']/parent::div[@class='input_inputError__fLUP9']")
ERROR_TEXT_LOGIN = (By.XPATH, "//span[text()='Ошибка']")
CREATE_ACCOUNT_BUTTON = (By.CSS_SELECTOR, "div.popUp_buttonRow__\\+W8JD > button.buttonPrimary[type='submit']")
SIGN_OUT_BUTTON = (By.CSS_SELECTOR, "button.btnSmall")
PLACE_LISTING_BUTTON = (By.XPATH, "//button[text()='Разместить объявление']")
AUTHORIZE_TEXT = (By.CSS_SELECTOR, "div.popUp_titleRow__M7tGg > h1.h1")
LISTING_NAME = (By.CSS_SELECTOR, "input[name='name']")
LISTING_DESCRIPTION = (By.CSS_SELECTOR, "textarea[name='description']")
LISTING_PRICE = (By.CSS_SELECTOR, "input[name='price']")
DROP_DOWN_CATEGORY = (By.CSS_SELECTOR, "input[name='category'] ~ button.dropDownMenu_arrowDown__pfGL1")
DROP_DOWN_CATEGORY_ITEM = (By.XPATH, "//button[span[text()='Технологии']]")
DROP_DOWN_TOWN = (By.CSS_SELECTOR, "input[name='city'] ~ button.dropDownMenu_arrowDown__pfGL1")
DROP_DOWN_TOWN_ITEM = (By.XPATH, "//button[span[text()='Казань']]")
ITEM_CONDITION = (By.CSS_SELECTOR, "div.radioUnput_inputRegular__FbVbr")
PUBLISH_BUTTON = (By.XPATH, "//button[text()='Опубликовать']")
LISTING_ITEM = (By.XPATH, "//h2[text()='" + LISTING_ITEM_TEXT + "']")
