from selenium.webdriver.common.by import By
from data import LISTING_ITEM_TEXT

LOGIN_BUTTON_HEADER = (By.CSS_SELECTOR, 'button.buttonSecondary:nth-child(1)')
NO_ACCOUNT_BUTTON = (By.CSS_SELECTOR, 'button.buttonSecondary:nth-child(2)')
EMAIL_INPUT = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[2]/div[1]/div/div/input')
PASSWORD_INPUT_1 = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[2]/div[2]/div/div/input')
PASSWORD_INPUT_2 = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[2]/div[3]/div/div/input')
CREATE_ACCOUNT_BUTTON = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[3]/button[1]')
USER_AVATAR = (By.XPATH, '//*[name()="svg" and contains(@class, "svgSmall")]')
USER_TEXT = (By.XPATH, '//*[@id="root"]/div/div[1]/div/div[1]/div/h3')
EMAIL_BORDER = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[2]/div[1]/div/div')
PWD_1_BORDER = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[2]/div[2]/div/div')
PWD_2_BORDER = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[2]/div[3]/div/div')
ERROR_TEXT_LOGIN = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[2]/div[1]/span')
EXISTING_EMAIL = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[2]/div[1]/div/div/input')
EXISTING_PASS = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[2]/div[2]/div/div/input')
SIGN_IN_BUTTON = (By.XPATH, '//*[@id="root"]/div/div[2]/div[5]/form/div[3]/button[1]')
SIGN_IN_HEADER = (By.CSS_SELECTOR, '#root > div > div.header_shell__zlCGj > div > button.buttonSecondary.inButtonText.undefined.inButtonText')
SIGN_OUT_BUTTON = (By.XPATH, '//*[@id="root"]/div/div[1]/div/div[1]/div/button')
PLACE_LISTING_BUTTON = (By.XPATH, '//*[@id="root"]/div/div[1]/div/button[2]')
AUTHORIZE_TEXT = (By.XPATH, '/html/body/div/div/div[2]/div[5]/form/div[1]/h1')
CREATE_LISTING = (By.XPATH, '//*[@id="root"]/div/div[1]/div/button')
LISTING_NAME = (By.XPATH, '//*[@id="root"]/div/div[2]/div/form/div[2]/div[1]/div/div/input')
LISTING_DESCRIPTION = (By.XPATH, '//*[@id="root"]/div/div[2]/div/form/div[4]/div/textarea')
LISTING_PRICE = (By.XPATH, '//*[@id="root"]/div/div[2]/div/form/div[5]/div/div/input')
DROP_DOWN_CATEGORY = (By.CSS_SELECTOR, "div.dropDownMenu_input__itKtw > button")
DROP_DOWN_CATEGORY_ITEM = (By.XPATH, '//*[@id="root"]/div/div[2]/div/form/div[2]/div[2]/div[2]/button[5]')
DROP_DOWN_TOWN = (By.XPATH, '//*[@id="root"]/div/div[2]/div/form/div[3]/div[1]/button')
DROP_DOWN_TOWN_ITEM = (By.XPATH, '//*[@id="root"]/div/div[2]/div/form/div[3]/div[2]/button[6]')
ITEM_CONDITION = (By.XPATH, '//*[@id="root"]/div/div[2]/div/form/fieldset/div/div[2]/div')
PUBLISH_BUTTON = (By.XPATH, '//*[@id="root"]/div/div[2]/div/form/button')
USER_PROFILE_ICON = (By.XPATH, '//*[@id="root"]/div/div[1]/div/div[1]/button')
LISTING_ITEM = (By.XPATH, "//h2[text()='" + LISTING_ITEM_TEXT + "']")
